import {Router} from 'express'
import {randomUUID} from 'node:crypto'
import {dbAll,dbGet,dbRun,dbTransaction,dbRunNoPersist} from '../db.js'
import {requireAuth,type AuthRequest} from '../middleware/auth.js'
const router=Router()
let initialized=false
router.use(requireAuth)
router.use((req:AuthRequest,res,next)=>{if(!['admin','manager','creator'].includes(req.auth!.role)){res.sendStatus(403);return}if(!initialized){dbRun('CREATE TABLE IF NOT EXISTS creator_chat (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, sender_id TEXT NOT NULL, from_admin INTEGER NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, read_at TEXT, request_id TEXT NOT NULL, UNIQUE(user_id,sender_id,request_id))');dbRun('CREATE INDEX IF NOT EXISTS creator_chat_user ON creator_chat(user_id,created_at)');initialized=true}next()})
function admin(req:AuthRequest){return ['admin','manager'].includes(req.auth!.role)}
router.get('/recipients',(req:AuthRequest,res)=>{if(!admin(req)){res.sendStatus(403);return}const q='%'+String(req.query.q??'').slice(0,150)+'%';const offset=Math.max(0,Math.floor(Number(req.query.offset)||0));res.json(dbAll("SELECT u.id,u.name,c.program,(SELECT COUNT(*) FROM creator_chat m WHERE m.user_id=u.id AND m.from_admin=0 AND m.read_at IS NULL) unread FROM users u JOIN creators c ON c.user_id=u.id WHERE u.role='creator' AND (u.name LIKE ? OR u.email LIKE ?) ORDER BY unread DESC,u.name,u.id LIMIT 50 OFFSET ?",[q,q,offset]))})
router.get('/',(req:AuthRequest,res)=>{const userId=admin(req)?String(req.query.userId??''):req.auth!.userId;if(!userId){res.status(400).json({error:'Alıcı seçin.'});return}const before=String(req.query.before??'');res.json(dbAll('SELECT * FROM creator_chat WHERE user_id=? '+(before?'AND rowid < (SELECT rowid FROM creator_chat WHERE id=? AND user_id=?) ':'')+'ORDER BY rowid DESC LIMIT 50',before?[userId,before,userId]:[userId]).reverse())})
router.patch('/:id/read',(req:AuthRequest,res)=>{const row=dbGet<{user_id:string;from_admin:number}>('SELECT user_id,from_admin FROM creator_chat WHERE id=?',[String(req.params.id)]);if(!row||(!admin(req)&&row.user_id!==req.auth!.userId)||Boolean(row.from_admin)===admin(req)){res.sendStatus(404);return}dbRun('UPDATE creator_chat SET read_at=COALESCE(read_at,?) WHERE id=?',[new Date().toISOString(),String(req.params.id)]);res.json({ok:true})})
router.post('/',(req:AuthRequest,res)=>{const {subject,body,requestId,audience,userId}=req.body??{};if(typeof subject!=='string'||!subject.trim()||subject.length>200||typeof body!=='string'||!body.trim()||body.length>10000||typeof requestId!=='string'||! /^[a-zA-Z0-9-]{20,64}$/.test(requestId)){res.status(400).json({error:'Konu (200 karakter) ve mesajı (10000 karakter) kontrol edin.'});return}
let recipients:string[]=[];if(admin(req)){if(['all','student_cinema','standard'].includes(audience)){recipients=dbAll<{user_id:string}>("SELECT c.user_id FROM creators c JOIN users u ON u.id=c.user_id WHERE u.role='creator'"+(audience==='all'?'':" AND COALESCE(c.program,'standard')=?"),audience==='all'?[]:[audience]).map(r=>r.user_id)}else if(audience==='direct'&&typeof userId==='string'&&dbGet("SELECT u.id FROM users u JOIN creators c ON c.user_id=u.id WHERE u.id=? AND u.role='creator'",[userId]))recipients=[userId];else{res.status(400).json({error:'Geçerli alıcı veya grup seçin.'});return}}else{if(!dbGet('SELECT id FROM creators WHERE user_id=?',[req.auth!.userId])){res.sendStatus(403);return}recipients=[req.auth!.userId]}
const now=new Date().toISOString();dbTransaction(()=>{for(const recipient of recipients)dbRunNoPersist('INSERT OR IGNORE INTO creator_chat (id,user_id,sender_id,from_admin,subject,body,created_at,request_id) VALUES (?,?,?,?,?,?,?,?)',[randomUUID(),recipient,req.auth!.userId,admin(req)?1:0,subject.trim(),body.trim(),now,requestId]);});res.status(201).json({sent:recipients.length})})
export default router
