import {useEffect,useState} from 'react'
import {api} from '../../api/client'
import {defaultPresentation,type Presentation} from '../landing/GuestPresentation'
export function AdminGuestPresentation({blocks}:{blocks:{id:string;title:string}[]}){
 const [settings,setSettings]=useState<Record<string,Presentation>>({}),[message,setMessage]=useState(''),[ready,setReady]=useState(false)
 useEffect(()=>{void api<Record<string,Presentation>>('/api/landing-presentation').then(data=>{setSettings(data);setReady(true)}).catch(()=>setMessage('Görünüm ayarları yüklenemedi.'))},[])
 async function save(){try{await api('/api/landing-presentation',{method:'PUT',body:JSON.stringify(settings)});setMessage('Görünüm kaydedildi.')}catch{setMessage('Görünüm kaydedilemedi.')}}
 return <details className="rounded-xl border border-white/10 p-4"><summary>Ziyaretçi görünümü: üç sütun, içerik sayısı ve banner genişliği</summary><p className="my-3 text-sm">Masaüstünde üç sütun; mobilde ekrana göre daralır. İçerik sayısı yalnızca ziyaretçi ana sayfasını sınırlar. Sıra ve gizleme mevcut bölüm kontrollerinden yönetilir.</p>{blocks.map(block=>{const value=settings[block.id]??defaultPresentation;const update=(patch:Partial<Presentation>)=>setSettings(current=>({...current,[block.id]:{...value,...patch}}));return <div key={block.id} className="my-3 flex flex-wrap items-center gap-3"><span className="min-w-48">{block.title}</span><select aria-label={block.title+' içerik sayısı'} disabled={!ready} value={value.count} onChange={e=>update({count:Number(e.target.value) as 3|6|9})}>{[3,6,9].map(n=><option key={n} value={n}>{n} içerik</option>)}</select><select aria-label={block.title+' genişlik'} value={value.width} disabled={!ready} onChange={e=>update({width:e.target.value as Presentation['width']})}><option value="normal">Normal genişlik</option><option value="wide">Geniş</option></select><select aria-label={block.title+' hizalama'} value={value.align} disabled={!ready} onChange={e=>update({align:e.target.value as Presentation['align']})}><option value="left">Sola hizalı</option><option value="center">Ortalanmış</option></select></div>})}<button type="button" disabled={!ready} onClick={()=>void save()} className="rounded bg-plooy-gold p-3 text-black">Görünümü kaydet</button><p role="status">{message}</p></details>
}
