import {useEffect,useRef,useState} from 'react'
import { createRandomId } from '../utils/id'
import {useLocation} from 'react-router-dom'
import {useTranslation} from 'react-i18next'
import {useAuth} from '../context/AuthContext'
import {api,resolveMediaUrl} from '../api/client'
import type {Banner} from '../types/banner'
function record(id:string,kind:string){try{let sessionId=sessionStorage.getItem('plooy_banner_session');if(!sessionId){sessionId=createRandomId();sessionStorage.setItem('plooy_banner_session',sessionId)}void api('/api/banners/'+id+'/events',{method:'POST',body:JSON.stringify({sessionId,kind})}).catch(()=>{})}catch{}}
function Card({banner:b}:{banner:Banner}){const ref=useRef<HTMLDivElement>(null);const {i18n}=useTranslation();const en=i18n.language.startsWith('en');useEffect(()=>{if(!ref.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){record(b.id,'view');observer.disconnect()}},{threshold:0.5});observer.observe(ref.current);return()=>observer.disconnect()},[b.id]);const content=<><img src={resolveMediaUrl(b.imageUrl)} alt={(en?b.titleEn:b.titleTr)||b.name} className={'w-full object-cover '+(b.size==='small'?'h-32':b.size==='large'?'h-80':'h-52')}/><div className="p-4"><span className="text-xs text-plooy-muted">{en?'Advertisement':'Reklam'}</span><h2 className="text-xl font-semibold">{(en?b.titleEn:b.titleTr)||b.titleTr}</h2><p>{(en?b.bodyEn:b.bodyTr)||b.bodyTr}</p></div></>;return <div ref={ref} className="overflow-hidden rounded-xl border border-white/10 bg-plooy-surface">{b.link?<a href={b.link} onClick={()=>record(b.id,'click')}>{content}</a>:content}</div>}
export function PageBanners({placement}:{placement:Banner['placement']}){const [items,setItems]=useState<Banner[]>([]);const {user}=useAuth();const {pathname}=useLocation();useEffect(()=>{let stopped=false;const refresh=()=>{void api<Banner[]>('/api/banners').then(data=>{if(!stopped)setItems(data)}).catch(()=>{})};refresh();const timer=window.setInterval(refresh,60000);return()=>{stopped=true;clearInterval(timer)}},[user?.id,pathname]);const visible=items.filter(b=>b.placement===placement);if(!visible.length)return null;return <aside className={'mx-auto max-w-7xl space-y-4 px-5 py-6 '+(placement==='top'?'mt-24':'')}>{visible.map(b=><Card key={b.id} banner={b}/>)}</aside>}
