/** Türkiye sinema / RTV lisans programları — YÖK tercih verilerinden derlendi (2025) */
export const TURKEY_FILM_SCHOOLS = [
  { id: 'afyon-kocatepe-sinema-tv', name: 'Afyon Kocatepe Üniversitesi — Sinema ve Televizyon', slug: 'afyon-kocatepe-sinema-tv' },
  { id: 'akdeniz-universitesi', name: 'Akdeniz Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'akdeniz-universitesi' },
  { id: 'altinbas-universitesi', name: 'Altınbaş Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'altinbas-universitesi' },
  { id: 'anadolu-sinema-tv', name: 'Anadolu Üniversitesi — Sinema ve Televizyon', slug: 'anadolu-sinema-tv' },
  { id: 'ankara-haci-bayram-veli-universitesi', name: 'Ankara Hacı Bayram Veli Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'ankara-haci-bayram-veli-universitesi' },
  { id: 'ankara-universitesi', name: 'Ankara Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'ankara-universitesi' },
  { id: 'antalya-belek-universitesi', name: 'Antalya Belek Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'antalya-belek-universitesi' },
  { id: 'ataturk-universitesi', name: 'Atatürk Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'ataturk-universitesi' },
  { id: 'aydin-adnan-menderes-universitesi', name: 'Aydın Adnan Menderes Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'aydin-adnan-menderes-universitesi' },
  { id: 'bahcesehir-sinema-tv', name: 'Bahçeşehir Üniversitesi — Sinema ve Televizyon', slug: 'bahcesehir-sinema-tv' },
  { id: 'baskent-film-tasarimi', name: 'Başkent Üniversitesi — Film Tasarımı ve Yönetimi', slug: 'baskent-film-tasarimi' },
  { id: 'baskent-universitesi', name: 'Başkent Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'baskent-universitesi' },
  { id: 'beykoz-universitesi', name: 'Beykoz Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'beykoz-universitesi' },
  { id: 'bitlis-eren-universitesi', name: 'Bitlis Eren Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'bitlis-eren-universitesi' },
  { id: 'bolu-abant-izzet-baysal-universitesi', name: 'Bolu Abant İzzet Baysal Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'bolu-abant-izzet-baysal-universitesi' },
  { id: 'cankiri-karatekin-sinema-tv', name: 'Çankırı Karatekin Üniversitesi — Sinema ve Televizyon', slug: 'cankiri-karatekin-sinema-tv' },
  { id: 'canakkale-onsekiz-mart-universitesi', name: 'Çanakkale Onsekiz Mart Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'canakkale-onsekiz-mart-universitesi' },
  { id: 'cukurova-universitesi', name: 'Çukurova Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'cukurova-universitesi' },
  { id: 'dicle-universitesi', name: 'Dicle Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'dicle-universitesi' },
  { id: 'duzce-universitesi', name: 'Düzce Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'duzce-universitesi' },
  { id: 'ege-universitesi', name: 'Ege Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'ege-universitesi' },
  { id: 'erciyes-universitesi', name: 'Erciyes Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'erciyes-universitesi' },
  { id: 'fenerbahce-universitesi', name: 'Fenerbahçe Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'fenerbahce-universitesi' },
  { id: 'firat-universitesi', name: 'Fırat Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'firat-universitesi' },
  { id: 'giresun-universitesi', name: 'Giresun Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'giresun-universitesi' },
  { id: 'gumushane-universitesi', name: 'Gümüşhane Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'gumushane-universitesi' },
  { id: 'harran-universitesi', name: 'Harran Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'harran-universitesi' },
  { id: 'hasan-kalyoncu-universitesi', name: 'Hasan Kalyoncu Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'hasan-kalyoncu-universitesi' },
  { id: 'hatay-mustafa-kemal-universitesi', name: 'Hatay Mustafa Kemal Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'hatay-mustafa-kemal-universitesi' },
  { id: 'inonu-universitesi', name: 'İnönü Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'inonu-universitesi' },
  { id: 'isik-sinema-tv', name: 'Işık Üniversitesi — Sinema ve Televizyon', slug: 'isik-sinema-tv' },
  { id: 'istanbul-arel-sinema-tv', name: 'İstanbul Arel Üniversitesi — Sinema ve Televizyon', slug: 'istanbul-arel-sinema-tv' },
  { id: 'istanbul-aydin-universitesi', name: 'İstanbul Aydın Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-aydin-universitesi' },
  { id: 'istanbul-beykent-universitesi', name: 'İstanbul Beykent Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-beykent-universitesi' },
  { id: 'istanbul-bilgi-universitesi', name: 'İstanbul Bilgi Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-bilgi-universitesi' },
  { id: 'istanbul-esenyurt-universitesi', name: 'İstanbul Esenyurt Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-esenyurt-universitesi' },
  { id: 'istanbul-gelisim-universitesi', name: 'İstanbul Gelişim Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-gelisim-universitesi' },
  { id: 'istanbul-kent-universitesi', name: 'İstanbul Kent Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-kent-universitesi' },
  { id: 'istanbul-kultur-universitesi', name: 'İstanbul Kültür Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-kultur-universitesi' },
  { id: 'istanbul-medipol-universitesi', name: 'İstanbul Medipol Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-medipol-universitesi' },
  { id: 'istanbul-nisantasi-universitesi', name: 'İstanbul Nişantaşı Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-nisantasi-universitesi' },
  { id: 'istanbul-okan-sinema-tv', name: 'İstanbul Okan Üniversitesi — Sinema ve Televizyon', slug: 'istanbul-okan-sinema-tv' },
  { id: 'istanbul-rumeli-universitesi', name: 'İstanbul Rumeli Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-rumeli-universitesi' },
  { id: 'istanbul-topkapi-universitesi', name: 'İstanbul Topkapı Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-topkapi-universitesi' },
  { id: 'istanbul-universitesi', name: 'İstanbul Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-universitesi' },
  { id: 'istanbul-yeni-yuzyil-universitesi', name: 'İstanbul Yeni Yüzyıl Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istanbul-yeni-yuzyil-universitesi' },
  { id: 'istinye-universitesi', name: 'İstinye Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'istinye-universitesi' },
  { id: 'izmir-ekonomi-sdm', name: 'İzmir Ekonomi Üniversitesi — Sinema ve Dijital Medya', slug: 'izmir-ekonomi-sdm' },
  { id: 'kadir-has-universitesi', name: 'Kadir Has Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'kadir-has-universitesi' },
  { id: 'karabuk-universitesi', name: 'Karabük Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'karabuk-universitesi' },
  { id: 'kastamonu-universitesi', name: 'Kastamonu Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'kastamonu-universitesi' },
  { id: 'kocaeli-universitesi', name: 'Kocaeli Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'kocaeli-universitesi' },
  { id: 'malatya-turgut-ozal-universitesi', name: 'Malatya Turgut Özal Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'malatya-turgut-ozal-universitesi' },
  { id: 'maltepe-universitesi', name: 'Maltepe Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'maltepe-universitesi' },
  { id: 'mardin-artuklu-universitesi', name: 'Mardin Artuklu Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'mardin-artuklu-universitesi' },
  { id: 'marmara-universitesi', name: 'Marmara Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'marmara-universitesi' },
  { id: 'mersin-universitesi', name: 'Mersin Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'mersin-universitesi' },
  { id: 'mimar-sinan-sinema-tv', name: 'Mimar Sinan Güzel Sanatlar Üniversitesi — Sinema ve Televizyon', slug: 'mimar-sinan-sinema-tv' },
  { id: 'munzur-universitesi', name: 'Munzur Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'munzur-universitesi' },
  { id: 'necmettin-erbakan-universitesi', name: 'Necmettin Erbakan Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'necmettin-erbakan-universitesi' },
  { id: 'nigde-omer-halisdemir-universitesi', name: 'Niğde Ömer Halisdemir Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'nigde-omer-halisdemir-universitesi' },
  { id: 'ondokuz-mayis-universitesi', name: 'Ondokuz Mayıs Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'ondokuz-mayis-universitesi' },
  { id: 'ordu-universitesi', name: 'Ordu Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'ordu-universitesi' },
  { id: 'sakarya-universitesi', name: 'Sakarya Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'sakarya-universitesi' },
  { id: 'selcuk-universitesi', name: 'Selçuk Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'selcuk-universitesi' },
  { id: 'sivas-cumhuriyet-universitesi', name: 'Sivas Cumhuriyet Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'sivas-cumhuriyet-universitesi' },
  { id: 'suleyman-demirel-universitesi', name: 'Süleyman Demirel Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'suleyman-demirel-universitesi' },
  { id: 'tekirdag-namik-kemal-universitesi', name: 'Tekirdağ Namık Kemal Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'tekirdag-namik-kemal-universitesi' },
  { id: 'trabzon-universitesi', name: 'Trabzon Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'trabzon-universitesi' },
  { id: 'uskudar-universitesi', name: 'Üsküdar Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'uskudar-universitesi' },
  { id: 'usak-universitesi', name: 'Uşak Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'usak-universitesi' },
  { id: 'van-yuzuncu-yil-universitesi', name: 'Van Yüzüncü Yıl Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'van-yuzuncu-yil-universitesi' },
  { id: 'yasar-universitesi', name: 'Yaşar Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'yasar-universitesi' },
  { id: 'yeditepe-universitesi', name: 'Yeditepe Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'yeditepe-universitesi' },
  { id: 'yozgat-bozok-universitesi', name: 'Yozgat Bozok Üniversitesi — Radyo, Televizyon ve Sinema', slug: 'yozgat-bozok-universitesi' },
  { id: 'diger', name: 'Diğer / Okulum listede yok', slug: 'diger' },
] as const
